### ISSUE TITLE
Use of association proxies

### ISSUE THREAD

**Issue by garytaylor** [JsonApiClient/json_api_client#94]
I am using your gem in my project and totally love it.  I am trying to give developers of our system to use our API as if it consisted of active record objects.  
One area which I feel needs improvement (and I am happy to do it) is support for the following syntax using proxies instead of returning arrays :-

```
  Blog.find("my blog").entries.find("an interesting entries")
```

Where a blog has many entries.

At the moment, :-

```
   Blog.find("my blog").entries
```

will return an array, so it has already requested ALL entries for the blog, but we only want 1 entry, but unless we use some form of association proxy, the syntax cannot be supported.

What I am proposing is to return an instance of a proxy which knows when "to_a" or "each" etc.. is called, it asks the real model class to return the instances.  But, if we do something like filter the list using 'where', then we can request the filtered data from the server (unless we have the data included - in which case we just filter the list in memory).  Hopefully you get the idea - it is similar to how active record works.

Please comment - would like to know your thoughts on it or even if you are already planning to support this syntax ?

Thanks

Gary

**Comment by chingor13** [comment]
The above example would be accomplished by something like:

```
Entry.where(blog_id: blog_id).find(entry_id)
```

This would skip the first api call (assuming you had the blog id already).

It's difficult to support that ActiveRecord association-like syntax because jsonapi spec really defines a hypermedia api (where you can browse links/relationships). The `entries` association could also already be present in the response via the compound document spec.

**Comment by senid231** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
